apiVersion: v1
kind: Secret
metadata:
  name: jfrog-registry-secret
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: eyJhdXRocyI6eyJ0cmlhbDR3NHdjcnguamZyb2cu
    aW8iOnsicmVnYXV0aCI6Imt1YmVybmV0ZXM6Y21WbWRHdHVPakF4T2pFM05qYzVOekEyTXpVNlZtdHdia2xOYUhsWGQxRlVjRE5OZUhoVVkyRjJWRXgzWWpkcCJ9fX0=
